Updated scripts

diff --git a/scripts/start_server b/scripts/start_server
--- a/scripts/start_server
+++ b/scripts/start_server
@@ -1,5 +1,11 @@
 #!/bin/bash
 cd /home/ec2-user/app
 source environment/bin/activate
+pip install supervisor
+if supervisord -c supervisord.conf; then
+    echo "Supervisor started successfully."
+else
+    echo "Failed to start supervisor."
+    exit 1
+fi
 supervisord -c supervisord.conf
-
